# Generated by Django 4.1.9 on 2024-01-12 22:15

import _hashlib
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content_md5",
                    models.CharField(db_index=True, default=_hashlib.openssl_md5, max_length=32, unique=True),
                ),
                ("file_name", models.CharField(max_length=512)),
                ("version_number", models.IntegerField()),
                ("created_at", models.DateTimeField(default=datetime.datetime.utcnow)),
                ("location", models.CharField(default="/", max_length=1024)),
                ("file", models.FileField(blank=True, null=True, upload_to="storage/")),
                ("extension", models.CharField(default="", max_length=512)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name="FileVersion",
        ),
    ]
