# Generated by Django 4.1.9 on 2024-01-12 23:22

import _hashlib
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_file_delete_fileversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="content_md5",
            field=models.CharField(db_index=True, default=_hashlib.openssl_md5, max_length=32),
        ),
    ]
